apiVersion: v2
name: wp-project-skeleton
description: A Helm chart to deploy WordPress project.
type: application
version: 0.5.16
appVersion: "0.5.16"
dependencies:
  - name: common
    version: 2.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: newrelic-php-agent
    version: 0.1.2
    repository: https://wp-digital.github.io/helm-charts
